README.md, gdgajubot.py, requirements.txt
Atualização do README
comando /book para pegar o livro do packtpub
easter eggs com java e ruby (Inicio do tretabot)
=> Novas funções

gdgajubot.py
Além disso, `get_events` agora recebe o parâmetro `config`, para que não seja necessária manter uma variável global.
Essas mudanças permitirão adicionar testes de unidade ao projeto.
=> Movida a lógica do bot para a classe GDGAjuBot

gdgajubot.py
A classe `Resources` agrupa as funções de acesso à Internet.
`GDGAjuBot` espera uma instância `Resources`, de forma que os testes a serem definidos não precisarão de acesso à Internet, através da definição de mocks dessas duas classes.
=> Adicionada a classe Resources

tests/test_gdgajubot.py
Testes simples para começar. Assim já dá pra colocar o travis pra funcionar direito :)
=> Adiciona testes simples para find_java, python e ruby

tests/test_gdgajubot.py
Para que os código de teste fiquem menos complexos.
=> Testes: "syntax sugar" na identificação do método chamado

.travis.yml, scripts/gdgajubot, setup.py
Foi definido os requisitos básicos do projeto no arquivo `setup.py`.
=> Definição de setup.py

gdgajubot.py, tests/test_gdgajubot.py
Adicionei o parâmetro para retornar uma quantidade específica de eventos. Atualmente com valor padrão de 5 eventos.
=> Adicionado parâmetro para a quantidade de eventos. #26

gdgajubot/gdgajubot.py, gdgajubot/util.py
Adicionado o comando /auto_book para enviar atualizações de /book.
Fix #7
=> Recurso experimental de envio de atualizações

requirements-dev.txt, requirements.txt, setup.py
Agora temos os arquivos
- requirements.txt
- requirements-dev.txt
E a entrada `install_requires` do setup.py referencia requirements.txt
=> Organização dos requisitos do projeto

Procfile, scripts/gdgajubot, scripts/heroku-worker.sh, setup.py
- Removido script `scripts/gdgajubot` e substituído por um entry point no `setup.py`
- Heroku worker colocado em um script separado
=> Refatorações

gdgajubot/gdgajubot.py, gdgajubot/util.py, tests/test_gdgajubot.py
- Remoção dos auto comandos
- Código de tratamento dos argumentos da linha de comando mais organizado
=> Refatorações e limpeza de código em geral

gdgajubot/gdgajubot.py
=> Ordena eventos do Facebook

gdgajubot/gdgajubot.py, tests/test_gdgajubot.py
Precisa organizar melhor, ajeitar testes, mas já funciona.
=> Adiciona suporte a múltiplos grupos

config/default_config.yaml, gdgajubot/gdgajubot.py, gdgajubot/util.py, requirements.txt, tests/test_gdgajubot.py
Adiciona suporte a arquivo de configuração.
=> Config file

gdgajubot/gdgajubot.py, tests/test_gdgajubot.py
Corrigido e aproveitando, /books retorna uma mensagem mais legal quando não tem livros :-)
=> Fix /books command

gdgajubot/__main__.py, gdgajubot/bot.py, gdgajubot/data/database.py, gdgajubot/data/resources.py, gdgajubot/util.py, tests/test_gdgajubot.py
Changes:
- entity `State` with a new schema (remember to drop the old table before deploy)
- better rules for send book in `ensure_daily_book`
- last sent time stored in timezone GMT-3
- some bugfixes
=> Rework in the daily book task

gdgajubot/bot.py, gdgajubot/data/resources.py, gdgajubot/util.py, tests/test_gdgajubot.py
Some changes to have a happier state dumping :smile:, i.e. having less database writes:
- Add a task to dump states every ten minutes.
- Add a new command `/dump_states` to manually dump before restart the bot, for instance.
=> Dump states happy

gdgajubot/util.py
Altera a probabilidade de respostas do `@do_not_spam` de 30% para 10%.
=> Reduz a quantidade de easter_eggs

README.md
Contribuição rápida adicionando alguns comandos no README.
=> Atualização do README.

gdgajubot/bot.py
Usa o parâmetro no decorator ao invés de testar dentro da função.
=> Atualiza list_users para decorator

gdgajubot/bot.py, gdgajubot/decorators.py, gdgajubot/util.py, tests/test_gdgajubot.py
Reescrevi os decorators com o propósito de ser:
- Mais fácil a manutenção
- Maior facilidade para incluir novos decorators
- Mais bonito :smile: 
- Mais pythônico :snake:
=> Reescrita dos decorators do bot

.github/CODEOWNERS
Vou restringir todas as PRs a terem pelo menos um membro do @GDGAracaju/bot-team aprovando antes de efetuar merge.
=> Adiciona @GDGAracaju/bot-team como code owner do projeto inteiro
